# Generated by Django 3.2.13 on 2022-07-06 03:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AddField(
            model_name='kb',
            name='partners',
            field=models.ManyToManyField(blank=True, related_name='partners', to=settings.AUTH_USER_MODEL),
        ),
    ]
