# Generated by Django 3.2.6 on 2022-06-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_kb_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='kb',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kb',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
