# Generated by Django 3.2.6 on 2022-06-15 23:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20220615_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kb',
            name='category',
        ),
        migrations.RemoveField(
            model_name='message',
            name='body',
        ),
        migrations.AddField(
            model_name='message',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
