# Generated by Django 3.2.13 on 2022-07-03 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_topic_kb_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kb',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
